version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  #Go application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      # Adjust these environment variables as needed
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: myuserd
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
